services:

  postgres:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=smidadb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready -U postgres"
  mongodb:
    image: mongo:7.0.6
    container_name: "mongodb"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=smidadb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
